name: PaperDue Plugin
version: 1.2.1
main: net.paperdue.factions.Main
author: SanoKei
description: Factions plugin for PaperDue.Net
api-version: 1.17.1

commands:
   f:
      description: Factions plugin